#!/usr/bin/python3

# SPDX-FileCopyrightText: 2024 Toki Makabe <s23c1130sm@s.chibakoudai.jp>
# SPDX-License-Identifier:BSD-3-Clause

import sys
import re

# 定数
BEFORE_SORT = 1
BEFORE_DESC = 2
BEFORE_INPUT = 3
BEFORE_OUTPUT = 4
BEFORE_NOAPPER_LOWER = 5
BEFORE_KUGIRI = 6
BEFORE_EXTRA = 7

sort_comm = 0 #ソートをする
desc_comm = 0 #ソートする＆降順で並べる
input_file = "" #インプットするテキストデータのパス
output_file = "" #アウトプットする場合のパス
NoApperLower_comm = 0 #大文字・小文字を区別しない
kugiri_comm = "," #区切り文字の変更
extra_comm = "" #一文字だけ摘出して、出力する
before_tmp = 0

moji_count = [[0 for _ in range(2)] for _ in range(200)]

moji_input_data = sys.stdin.read()

try:
    for line in sys.argv:
        # オプションだったら(先頭にハイフンがつく)
        if line[0] == '-':
            if line[1] == 'i':
                before_tmp = BEFORE_INPUT
                continue
            elif line[1] == 'o':
                before_tmp = BEFORE_OUTPUT
                continue
            elif line[1] == 's':
                sort_comm = 1
                continue
            elif line[1] == 'r':
                desc_comm = 1
                continue
            elif line[1] == 'a':
                NoApperLower_comm = 1
                continue
            elif line[1] == 'k':
                before_tmp = BEFORE_KUGIRI
                continue
            elif line[1] == 'h':
                print("文字をカウントして出力します \n-o:アウトプット指定(オプション)")
                print("-s:ソート(オプション・昇順) \n-r:ソート(オプション・降順)\n-a:大文字・小文字を区別しない(オプション) \n-k:区切り文字変更（オプション)\n")
                print("例： cat input.txt | ./counter -r -a -k #input.txtを入力 降順ソート 大文字と小文字を区別しない 区切り文字を':'に変更")
                exit(0)
            else:
                print("不明なコマンド -h(help)を参照\n", file=sys.stderr)
                exit(1)

        elif before_tmp == BEFORE_OUTPUT:
            output_file = line
            continue
        elif before_tmp == BEFORE_KUGIRI:
            kugiri_comm = line
            kugiri_comm = kugiri_comm.replace("\n","")
            continue

    #英語と数字のみにする
    moji_input_data = re.sub(r'[^a-zA-Z0-9]',"", moji_input_data)

    #大文字＆小文字を区別しないので、すべて大文字にする
    if NoApperLower_comm == 1:
        moji_input_data = moji_input_data.upper()

    #小文字の処理
    for i in range(ord('a'), ord('z')):
        moji_count[i][0] = moji_input_data.count(chr(i))
        moji_count[i][1] = chr(i)

    #大文字の処理
    for i in range(ord('A'), ord('Z')):
        moji_count[i][0] = moji_input_data.count(chr(i))
        moji_count[i][1] = chr(i)

    #数字の処理
    for i in range(ord('0'), ord('9')):
        moji_count[i][0] = moji_input_data.count(chr(i))
        moji_count[i][1] = chr(i)

    if desc_comm == 1:
        sort_moji = sorted(moji_count, key = lambda x:-x[0])
    elif sort_comm == 1:
        sort_moji = sorted(moji_count, key = lambda x:x[0])
    else:
        sort_moji = moji_count

    #別ファイルに出力する場合は
    if output_file != "":
        #改行文字を取り除く
        output_file = output_file.replace("\n","")
        f_save = open(output_file, "w",-1,"utf-8")
        if f_save == OSError:
            print("エラーが発生しました。ファイルを開けませんでした。", file=sys.stderr)
            exit(3)

        for i in range(0,200):
            if sort_moji[i][0] != 0:
                f_save.write(sort_moji[i][1])
                f_save.write(kugiri_comm)
                f_save.write(str(sort_moji[i][0]))
                f_save.write("\n")
    else:
        print("*************************")
        for i in range(0,200):
            if sort_moji[i][0] != 0:
                print(sort_moji[i][1],end='')
                print(kugiri_comm,end='')
                print(sort_moji[i][0])

except FileNotFoundError:
    print("ファイルを開けませんでした。(ファイルが見つかりません)", file=sys.stderr)
    exit(4)
except PermissionError:
    print("ファイルを開く権限がありません。", file=sys.stderr)
    exit(5)


        
